name: Lint Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Prettier for Web
        run: npm run format:web

      - name: Run ESLint for Web
        run: npm run lint:web

      

      
