name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,refactor,chore" 

  lint-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js # required by Prettier and ESLint 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install
          cd apps/web/web
          npm install
  
      - name: Run Prettier for Web
        run: npm run format:web

      - name: Run ESLint for Web
        run: npm run lint:web
  test-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install
          cd apps/web/web
          npm install

      - name: Run Tests
        run: |
            cd apps/web/web
            npm test -- --coverage

      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: apps/web/web/coverage

  lint-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js # required by Prettier and ESLint 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install
          cd apps/mobile/mobile
          npm install
  
      - name: Run Prettier for Mobile
        run: npm run format:mobile

      - name: Run ESLint for Mobile
        run: npm run lint:mobile
    
  test-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install
          cd apps/mobile/mobile
          npm install

      - name: Run Tests
        run: |
            cd apps/mobile/mobile
            npm test

      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: apps/mobile/mobile/coverage

